import Navbar from './components/navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from './components/Footer'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'SCOIN',
  description: 'Generated by create next app,tailwind css',
  
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo.png" />
      </head>
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
